version: 1.0

hunt:
  deleteAfterUpload: true
  downloadDir: "./temp"
  endesa:
    username: ""
    password: ""
    invoiceNameFormat: "DD-MM-YY"
  agua:
    username: ""
    password: ""
    invoiceNameFormat: "DD-MM-YY"

upload:
  folderIds:
     - agua: ""
     - endesa: ""
  duplicateBehaviour: "skip"
  credentialsFilePath: "/absolute/path/to/app-credentials-file"